Get topics
akin-fagbohun/everything-news-backend pull request #1
Opened 2022-03-28 15:25 UTC by datboyakin

database and testing is up and running. Review for first GET endpoint ready for merge with main branch.

2022-03-28 15:42 UTC, karlaferry commented on __tests__/app.test.js
> +        expect(res.body[0]).toMatchObject({
I would make sure that I test all of the objects inside the array and not just the index zero! You could make use of a forEach + expect.any just to check that the properties exist and the values are in correct data types. No need to check exact values for now.

2022-03-28 15:42 UTC, karlaferry commented on index.js
> +app.get('/api/topics', async (req, res, next) => {
Please extract your controllers and models!

2022-03-28 15:46 UTC, karlaferry requested changes
I've left some comments on improving this so have a look at them please :) Submit it again for review when you're done! Looks good so far though 👍🏼

2022-03-29 09:40 UTC, aswain03 commented
Good work on implementing the feedback Akin, nicely done!

2022-03-29 11:45 UTC, merged